name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      artifact-name: firmware
    secrets: inherit

  upload:
    name: Upload firmware
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: firmware

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: firmware

