name: Build ZMK Firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your config
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget git python3-pip cmake ninja-build gperf ccache dfu-util device-tree-compiler qemu-system-arm
          pip3 install west

      - name: Init west & fetch ZMK
        run: |
          west init -l config
          west update
          west zephyr-export

      - name: Build firmware
        run: |
          west build -s zmk/app -d build/left -b seeeduino_xiao_ble -- -DSHIELD=cannonball_ll_left
          west build -s zmk/app -d build/right -b seeeduino_xiao_ble -- -DSHIELD=cannonball_ll_right

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: |
            build/left/zephyr/zmk.uf2
            build/right/zephyr/zmk.uf2
